# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Index and deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: node ./scripts/indexer
    - name: GH Pages deploy
      # You may pin to the exact commit or the version.
      # uses: Cecilapp/GitHub-Pages-deploy@f26df39a27b93cae2c6aac5e07fdc556e8770247
      uses: Cecilapp/GitHub-Pages-deploy@3.1.0
      with:
        # A verified email.
        email: dothq-robot@users.noreply.github.com
        build_dir: CDN
